
package View;

import Controller.Util;
import Model.Model;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class JFramePrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFramePrincipal.class.getName());

    /**
     * Creates new form JFramePrincipal
     */
    ArrayList<Float> metricas = new ArrayList<>();
    long tempoInicio,tempoFim;
    DefaultTableModel model ;


    public JFramePrincipal() {
        initComponents();
        pnlResultado.setVisible(false);
        Model.lista = new ArrayList<>();
        model = (DefaultTableModel) tbl_Ordenacao.getModel();
    }
    public void carregarTabela(){
       String metodo = cmb_Metodos.getSelectedItem().toString();
       String qtdeComparacoes = txtQtdeComparacoes.getText();
       String qtdeNumero = txtQtdeNumero.getText();
       String qtdeTrocas = txtQtdeTrocas.getText();
       String tempo = txtTempo.getText();
       
       model.addRow(new Object []{metodo,qtdeNumero,qtdeComparacoes,qtdeTrocas,tempo});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomArquivo = new javax.swing.JLabel();
        lblMetodos = new javax.swing.JLabel();
        txtNomeArquivo = new javax.swing.JTextField();
        btnAbrir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        cmb_Metodos = new javax.swing.JComboBox<>();
        btnExecutar = new javax.swing.JButton();
        pnlResultado = new javax.swing.JPanel();
        lblQtdeNumero = new javax.swing.JLabel();
        txtQtdeNumero = new javax.swing.JTextField();
        lblQtdeComparacao = new javax.swing.JLabel();
        txtQtdeComparacoes = new javax.swing.JTextField();
        lblQtdeTrocas = new javax.swing.JLabel();
        txtQtdeTrocas = new javax.swing.JTextField();
        lblTempo = new javax.swing.JLabel();
        txtTempo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ordenacao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa e Ordenação");

        lblNomArquivo.setText("Nome Arquivo");

        lblMetodos.setText("Métodos de Ordenação");

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(this::btnAbrirActionPerformed);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        cmb_Metodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolha", "Seleção", "Inserção", "Pente", "ShellSort", "HeapSort" }));

        btnExecutar.setText("Executar");
        btnExecutar.addActionListener(this::btnExecutarActionPerformed);

        lblQtdeNumero.setText("Quantidade de Números: ");

        txtQtdeNumero.setEditable(false);
        txtQtdeNumero.setEnabled(false);

        lblQtdeComparacao.setText("Quantidae Comparações: ");

        txtQtdeComparacoes.setEditable(false);
        txtQtdeComparacoes.setEnabled(false);

        lblQtdeTrocas.setText("Quantidade Trocas: ");

        txtQtdeTrocas.setEditable(false);
        txtQtdeTrocas.setEnabled(false);

        lblTempo.setText("Tempo (ms): ");

        txtTempo.setEditable(false);
        txtTempo.setEnabled(false);

        tbl_Ordenacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Métodos", "Qtde de Números", "Qtde Comparações", "Qtde Trocas", "Tempo (ms)"
            }
        ));
        jScrollPane1.setViewportView(tbl_Ordenacao);

        javax.swing.GroupLayout pnlResultadoLayout = new javax.swing.GroupLayout(pnlResultado);
        pnlResultado.setLayout(pnlResultadoLayout);
        pnlResultadoLayout.setHorizontalGroup(
            pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlResultadoLayout.createSequentialGroup()
                        .addGroup(pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResultadoLayout.createSequentialGroup()
                                    .addComponent(lblQtdeNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(pnlResultadoLayout.createSequentialGroup()
                                    .addComponent(lblQtdeComparacao)
                                    .addGap(22, 22, 22)))
                            .addGroup(pnlResultadoLayout.createSequentialGroup()
                                .addGroup(pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQtdeTrocas)
                                    .addComponent(lblTempo))
                                .addGap(53, 53, 53)))
                        .addGroup(pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtQtdeComparacoes)
                            .addComponent(txtQtdeNumero)
                            .addComponent(txtQtdeTrocas, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtTempo))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlResultadoLayout.setVerticalGroup(
            pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdeNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtdeNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdeComparacao)
                    .addComponent(txtQtdeComparacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdeTrocas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdeTrocas))
                .addGap(18, 18, 18)
                .addGroup(pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempo)
                    .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_Metodos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnLimpar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Metodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExecutar)
                .addGap(18, 18, 18)
                .addComponent(pnlResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        if(Model.listaOriginal == null || Model.lista.isEmpty()){
           JOptionPane.showMessageDialog(this, "O arquivo não foi carregado para a lista!","Erro",JOptionPane.ERROR_MESSAGE);
           
        }
        Model.retornarListaOriginal();
        pnlResultado.setVisible(true);
        pack();
         
         switch(cmb_Metodos.getSelectedIndex()){
             case 0:
                  //bolha
                 metricas.clear();
                 tempoInicio = System.nanoTime();
                 metricas.addAll(Controller.Ordenacao.bolha(Model.lista));
                 tempoFim = System.nanoTime();                 
                 metricas.add((float)(tempoFim - tempoInicio)/1000000);
                 break;
             case 1:
                      //seleção
                 metricas.clear();
                 tempoInicio = System.nanoTime();
                 metricas.addAll(Controller.Ordenacao.selecao(Model.lista));
                 tempoFim = System.nanoTime();                 
                 metricas.add((float)(tempoFim - tempoInicio)/1000000);

                 break;
                 
             case 2:
                  //inserção
                 metricas.clear();
                 tempoInicio = System.nanoTime();
                 metricas.addAll(Controller.Ordenacao.insercao(Model.lista));
                 tempoFim = System.nanoTime();                 
                 metricas.add((float)(tempoFim - tempoInicio)/1000000);

                  
                 break;
             case 3:
                    //pente
                 metricas.clear();
                 tempoInicio = System.nanoTime();
                 metricas.addAll(Controller.Ordenacao.pente(Model.lista));
                 tempoFim = System.nanoTime();                 
                 metricas.add((float)(tempoFim - tempoInicio)/1000000);

                 
                 break;
             case 4:
                   //shellsort
                 metricas.clear();
                 tempoInicio = System.nanoTime();
                 metricas.addAll(Controller.Ordenacao.shell(Model.lista));
                 tempoFim = System.nanoTime();
                 metricas.add((float) (tempoFim - tempoInicio) / 1000000);
                 break;
              case 5:
                   //heapsort
                 metricas.clear();
                 tempoInicio = System.nanoTime();
                 metricas.addAll(Controller.Ordenacao.heap(Model.lista));
                 tempoFim = System.nanoTime();
                 metricas.add((float) (tempoFim - tempoInicio) / 1000000);
                 break;
             default:
                    throw new AssertionError();
         }
        txtQtdeNumero.setText("" + Model.lista.size());
        txtQtdeComparacoes.setText("" + metricas.get(0));
        txtQtdeTrocas.setText("" + metricas.get(1));
        txtTempo.setText("" + metricas.get(2));

        carregarTabela();

    }//GEN-LAST:event_btnExecutarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        if(txtNomeArquivo.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Informe nome do arquivo","Atenção",JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(Util.carregarArquivo(txtNomeArquivo.getText(), Model.lista)){
                Model.salvarListaOriginal();
                JOptionPane.showMessageDialog(this, "Lista carregada com sucesso!","Sucesso",JOptionPane.INFORMATION_MESSAGE);

            }else{
                 JOptionPane.showMessageDialog(this, "Problema para ler o arquivo e carregar lista","Erro",JOptionPane.ERROR_MESSAGE);
                 txtNomeArquivo.setText("");
                 txtNomeArquivo.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNomeArquivo.setText("");
        Model.lista.clear();
        cmb_Metodos.setSelectedIndex(0);
        txtQtdeNumero.setText("");
        txtQtdeComparacoes.setText("");
        txtQtdeTrocas.setText("");
        txtTempo.setText("");
        txtNomeArquivo.requestFocusInWindow();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmb_Metodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMetodos;
    private javax.swing.JLabel lblNomArquivo;
    private javax.swing.JLabel lblQtdeComparacao;
    private javax.swing.JLabel lblQtdeNumero;
    private javax.swing.JLabel lblQtdeTrocas;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JPanel pnlResultado;
    private javax.swing.JTable tbl_Ordenacao;
    private javax.swing.JTextField txtNomeArquivo;
    private javax.swing.JTextField txtQtdeComparacoes;
    private javax.swing.JTextField txtQtdeNumero;
    private javax.swing.JTextField txtQtdeTrocas;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables
}
