package view;


import controller.Arquivo;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    
     StringBuffer palavraDigitada = new StringBuffer();
     int ocorrencias = 0;
     ArrayList<String> lista = new ArrayList<>();
     
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        pnl_Pesquisa.setVisible(false);
    }
/**
 * Metódo que tem como objetivo destacar em AMARELO as palavras digitadas no campo de pesquisar
 * @param palavra: utilizado como parâmetro para buscar as palavras dentro do arquivo 
 */
    private void destacarPalavraPesquisa(String palavra){
        Highlighter destaque = txta_Texto.getHighlighter();
        
        destaque.removeAllHighlights();
        
        if(palavra.isEmpty()){
            return;
        }
        String texto = txta_Texto.getText();
        Highlighter.HighlightPainter pintor = new DefaultHighlighter.DefaultHighlightPainter(Color.YELLOW);
        
        for(int i = 0; (i + palavra.length()) <= texto.length(); i++){
            if(texto.substring(i, i + palavra.length()).equalsIgnoreCase(palavra)){
                try{
                    destaque.addHighlight(i, i + palavra.length(), pintor);
                }catch(BadLocationException e){
                    JOptionPane.showMessageDialog(null,"Erro ao destacar a palavra/letra","Alerta",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Pesquisa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_Texto = new javax.swing.JTextArea();
        lblTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Pesquisa = new javax.swing.JTextField();
        lblOcorrencia = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        txtOcorrencia = new javax.swing.JTextField();
        lblNomeArquivo = new javax.swing.JLabel();
        txtNomeArquivo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txta_Texto.setEditable(false);
        txta_Texto.setColumns(20);
        txta_Texto.setRows(5);
        jScrollPane1.setViewportView(txta_Texto);

        lblTexto.setText("Texto");

        jLabel1.setText("Palavra de Pesquisa");

        txt_Pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PesquisaKeyTyped(evt);
            }
        });

        lblOcorrencia.setText("Ocorrências:");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        txtOcorrencia.setEditable(false);
        txtOcorrencia.setEnabled(false);

        javax.swing.GroupLayout pnl_PesquisaLayout = new javax.swing.GroupLayout(pnl_Pesquisa);
        pnl_Pesquisa.setLayout(pnl_PesquisaLayout);
        pnl_PesquisaLayout.setHorizontalGroup(
            pnl_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PesquisaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnl_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PesquisaLayout.createSequentialGroup()
                        .addComponent(lblTexto)
                        .addGap(468, 468, 468))
                    .addGroup(pnl_PesquisaLayout.createSequentialGroup()
                        .addGroup(pnl_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_PesquisaLayout.createSequentialGroup()
                                .addComponent(lblOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_PesquisaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(txt_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpar)
                .addGap(44, 44, 44))
        );
        pnl_PesquisaLayout.setVerticalGroup(
            pnl_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PesquisaLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnl_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PesquisaLayout.createSequentialGroup()
                        .addComponent(lblOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PesquisaLayout.createSequentialGroup()
                        .addComponent(txtOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnLimpar)
                .addGap(12, 12, 12)
                .addComponent(lblTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblNomeArquivo.setText("Nome do Arquivo:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnl_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeArquivo)
                    .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(pnl_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txta_Texto.setText("");
        txtOcorrencia.setText("");
        txt_Pesquisa.setText("");
        palavraDigitada = new StringBuffer();
        txtNomeArquivo.setText("");
        txta_Texto.getHighlighter().removeAllHighlights();//remove a palavra destaque dando clicado em limpar
        pnl_Pesquisa.setVisible(false);
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txt_PesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PesquisaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isISOControl(c)) {
            palavraDigitada.append(c);
        } else {
            palavraDigitada = new StringBuffer(txt_Pesquisa.getText());
        }

        ocorrencias = 0;

        String palavra = txt_Pesquisa.getText() + evt.getKeyChar();
        String texto = txta_Texto.getText();

        if (!palavra.isEmpty()) {
            for (int i = 0; i + palavra.length() <= texto.length(); i++) {
                if (texto.substring(i, i + palavra.length()).equalsIgnoreCase(palavra)) {
                    ocorrencias++;
                }
            }
        }
        txtOcorrencia.setText(String.valueOf(ocorrencias));
        destacarPalavraPesquisa(palavra);//chama o método destacar palavra
    }//GEN-LAST:event_txt_PesquisaKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Arquivo arquivo = new Arquivo();
        lista.clear();
        if(!arquivo.carregarArquivo(txtNomeArquivo.getText(),lista)){
            JOptionPane.showMessageDialog(this,"Erro ao carregar arquivo!","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        txta_Texto.setText("");
        //percorre cada elemento da lista
        for (String linha : lista) {
            txta_Texto.append(linha + "\n");//adiciona no textArea o contéudo 
        }
        pnl_Pesquisa.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeArquivo;
    private javax.swing.JLabel lblOcorrencia;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JPanel pnl_Pesquisa;
    private javax.swing.JTextField txtNomeArquivo;
    private javax.swing.JTextField txtOcorrencia;
    private javax.swing.JTextField txt_Pesquisa;
    private javax.swing.JTextArea txta_Texto;
    // End of variables declaration//GEN-END:variables
}
